### ISSUE TITLE
node crashing when sending thousands of tnx continuously 

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#103]
It seems that there's issue with goroutine of txpool and feed event

```
goroutine 2050658 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6ed8080, 0xc042565368)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050659 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6ed82c0, 0xc0425653f8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050633 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c10172e0, 0xc282f86238)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050634 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c4f34240, 0xc282f86778)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050635 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2a345e600, 0xc282f86fc0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050636 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc26629ef20, 0xc0c6b71858)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050637 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28dd1bc60, 0xc2465ce4d0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050660 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2a2d69aa0, 0xa3bda91681d05abd)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050661 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28c0cebc0, 0xc06b9941b0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050662 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2b1e4b880, 0xc06b9941c8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050300 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28a26e320, 0xc289f35370)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050638 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c7318660, 0xc2465cefd0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050639 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c7319080, 0xc2465cf158)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050640 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c7319960, 0xc2465cf298)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050641 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6453980, 0xc2465cf370)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050674 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc251a3a420, 0xc2465cf450)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050675 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc251a3a740, 0xc2465cf5b0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050676 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc251a3ae60, 0xc2465cf620)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050677 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc043098d20, 0xc2465cf8a8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050678 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc043099600, 0xc2465cf920)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050679 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc206b06ca0, 0xc2465cf9a0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050680 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc206b07620, 0xc2465cfb50)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050681 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2627c6d00, 0xc2465cfbc8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050682 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2bc180140, 0xc2465cfd70)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050683 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2bc180a60, 0xc2465cff90)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050301 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28a26ee00, 0xc289f353b8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050302 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28a26f1c0, 0xc289f353c8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050303 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28a26f780, 0xc289f353d8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050304 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28a26fc80, 0xc289f353e8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050305 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc1f0a06ba0, 0xc289f35408)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050690 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc1d8e2cda0, 0xc289f35430)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050691 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc1d8e2df40, 0xc289f35448)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050692 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc20445da60, 0xc289f35458)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050693 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2407e8740, 0xc289f354a0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050694 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2407e9040, 0xc289f354c0)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050695 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2407e9a60, 0xc289f35510)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050696 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc12dba41a0, 0xc289f35538)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050697 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc12dba52a0, 0xc289f35548)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050698 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc1c30dee80, 0xc289f35560)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050699 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc1c30df960, 0xc289f35580)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050700 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc0d0726da0, 0xc289f355a8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050701 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc17e5add40, 0xc289f355d8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050702 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc0e69722e0, 0xc289f355f8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050703 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc0e8a7a560, 0xc289f35648)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050706 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc28b466340, 0xc2c5867620)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050707 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afc0e0, 0xc2c5867650)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050708 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afc400, 0xc2c5867660)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050709 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afc7a0, 0xc2c5867680)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050710 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afce40, 0xc2c5867698)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050711 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afd740, 0xc2c58676c8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050712 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afda00, 0xc2c58676e8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050713 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc2c6afdd00, 0xc2c58676f8)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:1098 +0x17f8

goroutine 2050714 [chan receive, 52 minutes]:
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0067fc0b0, 0xe93b60, 0xc0b6bf8940, 0xc2c5867720)
	/home/admin/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/event/feed.go:133 +0x12f
created by github.com/ethereum/go-ethereum/core.(*TxPool).promoteExecutables
	/home/admin/gonex/build/_workspace/sr^C
```

**Comment by Zergity** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/19705
