### ISSUE TITLE
eth: reset miner, engine, and txpool when calling SetHead to prevent crashes

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#112]
https://github.com/ethereum/go-ethereum/pull/16713

> This small change fixes a bug in **tx_pool.go** which causes geth to crash in certain cases when debug.setHead is used.
> 
> I discovered this bug while running a single-node, private PoA network for testing purposes. Here are the steps I took to consistently produce the crash:
> 
> 1. Start a single-node, private PoA network (I used puppeth and [followed this guide](https://hackernoon.com/setup-your-own-private-proof-of-authority-ethereum-network-with-geth-9a0a3750cda8) as a starting point). Be sure to enable the RPC API with the flag: `--rpcapi 'miner,debug'`.
> 2. Mine at least one block. If you need to start the miner, you can use the ["miner_start" endpoint](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#miner_start) of the JSON RPC API.
> 3. Stop the miner via the ["miner_stop" endpoint](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#miner_stop).
> 4. Set the head to a previous block number via the ["debug_setHead" endpoint](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_sethead).
> 5. Start the miner again.
> 6. Geth crashes with a stack trace that looks like the following:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x447559f]
> 
> goroutine 75 [running]:
> github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
> 	/Users/alex/programming/go/src/github.com/ethereum/go-ethereum/core/types/block.go:310
> github.com/ethereum/go-ethereum/core.(*TxPool).reset(0xc420241dc0, 0xc420578b40, 0xc420578d80)
> 	/Users/alex/programming/go/src/github.com/ethereum/go-ethereum/core/tx_pool.go:370 +0x6bf
> github.com/ethereum/go-ethereum/core.(*TxPool).loop(0xc420241dc0)
> 	/Users/alex/programming/go/src/github.com/ethereum/go-ethereum/core/tx_pool.go:289 +0x504
> created by github.com/ethereum/go-ethereum/core.NewTxPool
> 	/Users/alex/programming/go/src/github.com/ethereum/go-ethereum/core/tx_pool.go:253 +0x4ed
> ```
> I believe this is happening because when the [`ChainHeadEvent` is received in **tx_pool.go**](https://github.com/ethereum/go-ethereum/blob/c4a4613d9504db43a26a3c79dda8bf6be0d1237a/core/tx_pool.go#L283), the variable `head` refers to a block that no longer exists. We can detect this cause by checking if the block number of `head` is greater than the current block number. And if that is the case, we can fix it by simply setting `head` to the current block.
> 
> After making this change, I tested it manually using the steps described above and observed that geth no longer crashes and continues to mine starting from the new block number. I also ran `make test` to ensure that all the existing tests still pass (they do). However, there still could be some unintended side effects I'm not aware of.
> 
> If we would like to add a test case for this, I would be happy to take a stab at it and include it in this PR. I just need some advice on where the test should live and how to get started on writing it.

**Comment by hadv** [comment]
Superseded by https://github.com/ethereum/go-ethereum/pull/19308
