### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#220]
Panic error when feeding price due to invalid block 

#### System information

Geth version: `gonex 2.0.2-unstable\Endurio-test`
OS & Version: OSX
Commit hash : `00677a718087e05b36acdd4c9b18ba079af6c7b9`

#### Steps to reproduce the behaviour
- change feed price to 1 after some randomness price

#### Backtrace

````
ERROR[06-12|11:04:18.008]
########## BAD BLOCK #########
Chain config: {ChainID: 111111 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5 ConstantinopleFix: <nil> Engine: dccs {ThangLong: 90 Epoch: 30 Contract: 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF Endurio: 120 PriceDuration: 40 PriceInterval: 3 AbsorptionLength: 20}}

Number: 277
Hash: 0xeb6f38e8b8cc9ea727daa316f790841cbce7471f6876ae3fdec24138d4b50712


Error: invalid merkle root (remote: c4afa4e9baae16634b26c423bc0e5c95b0e88490e3f8c47f4220d79a18f4feda local: 46a7fc62c6ad0229752592f17b1ec36b7969267faa158d2b2d7f1cab27b490ed)
##############################

INFO [06-12|11:04:18.701] Successfully sealed new block            number=277 sealhash=ee87d9…0b520c hash=19bbe3…29a2c4 elapsed=2.683s
INFO [06-12|11:04:18.701] 🔨 mined potential block                  number=277 hash=19bbe3…29a2c4
ERROR[06-12|11:04:18.702] Failed to reset txpool state             err="missing trie node d0adcc48377465c296ccb840a96747c89f27c84c012f313e8b39c18a9cc4e6f1 (path )"
INFO [06-12|11:04:18.703] offset                                   signer position=2 previous signer position=2 len(signers)=3 offset=2
ERROR[06-12|11:04:18.703] Failed to create mining context          err="missing trie node d0adcc48377465c296ccb840a96747c89f27c84c012f313e8b39c18a9cc4e6f1 (path )"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4330675]

goroutine 116 [running]:
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0x0, 0x0, 0x0, 0x0, 0x1)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:424 +0x85
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetOrNewStateObject(0x0, 0x0, 0x0, 0x0, 0xc053996850)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/statedb.go:454 +0x3f
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*RealBackend).callContract(0xc04dc9f800, 0x4ee53e0, 0xc0000ba018, 0x0, 0x0, 0x0, 0xc05057dc20, 0x2faf080, 0xc03423f620, 0xc03423f640, ...)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/abi/bind/backends/real.go:249 +0xa8
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*RealBackend).CallContract(0xc04dc9f800, 0x4ee53e0, 0xc0000ba018, 0x0, 0x0, 0x0, 0xc05057dc20, 0x0, 0x0, 0x0, ...)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/abi/bind/backends/real.go:157 +0x173
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc05057dc20, 0xc050b55660, 0x4ac0520, 0xc000482d38, 0x4cba862, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go:151 +0x508
github.com/ethereum/go-ethereum/contracts/nexty/endurio/stable.(*StableTokenCaller).TotalSupply(0xc000482d30, 0x0, 0xc078563412, 0x4ed6120, 0xc04dc9f800)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/contracts/nexty/endurio/stable/StableToken.go:3708 +0x8d
github.com/ethereum/go-ethereum/consensus/dccs.GetStableTokenSupply(0x0, 0x4eef2c0, 0xc008cac000, 0xc04dc9f740, 0xc00981fac8, 0x1)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/dccs/price_engine.go:304 +0x160
github.com/ethereum/go-ethereum/consensus/dccs.(*Dccs).RemainToAbsorbStat(0xc0001a6080, 0x4eef2c0, 0xc008cac000, 0x115, 0x0, 0x0)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/dccs/dccs.go:1652 +0x71
github.com/ethereum/go-ethereum/ethstats.(*Service).assembleBlockStats(0xc0002049a0, 0xc0096781b0, 0xc050b55c50)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:561 +0x3ed
github.com/ethereum/go-ethereum/ethstats.(*Service).reportBlock(0xc0002049a0, 0xc00922e090, 0xc0096781b0, 0x3, 0x1)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:511 +0x4d
github.com/ethereum/go-ethereum/ethstats.(*Service).loop(0xc0002049a0)
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:260 +0x98e
created by github.com/ethereum/go-ethereum/ethstats.(*Service).Start
	/Users/hadv/work/github/hadv/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:124 +0x5a
````

**Comment by Zergity** [comment]
This happens because of the StableToken supply is initialized with zero supply. We will need either a logic to handle the zero supply case, or do not let the supply go to zero at all.

**Comment by hadv** [comment]
this might be difference one when price set to 1, may not related to zero supply due to this bug found by running endurio-test branch that already pre-minted some token

**Comment by Zergity** [comment]
Right. I messed up those two. This one is fixed by https://github.com/nextyio/gonex/commit/a2852c87e6bd0ae8b05615ec22d4520a0e6c09f2
